version: '2.1'
services:
   app:
      container_name: app_container
      build: .
      ports:
         -  "8086:8080"
         -  "8087:8087"
      environment:
         app.home.title: "variable from docker compose"
         spring.datasource.url: "jdbc:postgresql://db:5432/testdb"
         spring.datasource.username: "postgres"
         spring.datasource.password: "postgres"
         spring.jpa.hibernate.ddl-auto: update
      networks:
         - "test_network"
   db:
      container_name: db_container
      image: postgres:14-alpine
      ports:
         -  "5433:5432"
      environment:
         POSTGRES_USER: "postgres"
         POSTGRES_PASSWORD: "postgres"
         POSTGRES_DB: "testdb"
      volumes:
         -  myvolume:/var/lib/postgresql/data
      networks:
         - "test_network"
networks:
   test_network:

volumes:
   myvolume:
